In [2]:
import torch

A = torch.arange(9).reshape(3,3)

print(A)

A_T = A.T

print(A.T)

A_T_T = A_T.T

print(A_T_T)

print(A_T_T == A)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [6]:
A = A
B = torch.arange(1,10).reshape(3,3)

A_T_plus_B_T = A.T + B.T
print(A_T + B.T)

A_plus_B__T = (A+B).T
print(A_plus_B__T)

tensor([[ 1,  7, 13],
        [ 3,  9, 15],
        [ 5, 11, 17]])
tensor([[ 1,  7, 13],
        [ 3,  9, 15],
        [ 5, 11, 17]])


In [12]:
A = torch.rand(9).reshape(3,3)
A + A.T


tensor([[1.7111, 0.9797, 0.4632],
        [0.9797, 0.9689, 1.0270],
        [0.4632, 1.0270, 0.2997]])

In [ ]:
X = torch.rand((2, 3, 4))
len(X)

2

len(X) always corresponds to the length of the first axis.

In [18]:
A = torch.arange(9).reshape(3,3)
print(A)
A = A.sum(axis=1)
A

# This sums along the columns.

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([ 3, 12, 21])

When traveling between two points in downtown manhattan, the distance you need to cover in terms of coordinates is streets horizontal and streets vertical. You cannot travel diagonally.

In [20]:
X = torch.rand(2,3,4)

print(X.sum(0).shape) # (3,4)

print(X.sum(1).shape) # (2, 4)

print(X.sum(2).shape) # (2, 3)

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])


In [23]:
# Computes the scalar magnitude.
torch.linalg.norm(X)

tensor(3.1135)

If you compute (AB)C, you end up with an additional (10, 5) matrix, then an additional (10, 14) matrix.

If you compute A(BC), you end up with an additional (16, 14) matrix, then an additional (10, 14) matrix.

So it's more efficient to compute (AB)C.

In [32]:
A = torch.rand(100, 200)
B = torch.rand(100, 200)
C = torch.rand(100, 200)

A_B_C = torch.stack([A, B, C])

B_slice = A_B_C[1, :, :]

print(B == B_slice)

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])
